export default {
    'app.name':'Name',
    'app.search':'Search',
    'app.type':'Type',
    'app.all':'All',
    'app.id':'Id',
    'app.actions':'Actions',
    'app.styleSheet':'Style Sheet',
    'app.inlineEditingAssistant':'Inline editing assist',
    'app.htmlModel':'HTML Model',
    'app.code':'Code',
    'app.attributes':'Attributes',
    'app.choose':'Choose...',
    'app.cancel':'Cancel',
    'app.save':'Save',
    'app.requiredFields':'Required Fields',
    'app.addContentTemplate':'Add content template',
    'app.pressCtrlSpaceToOpenContentAssistMenu':'(press ctrl + space to open content assist menu)',
    'app.noTemplateFound"': 'No template found"',
    'app.doYouReallyWanttoDelete':'Do you really want to delete ?',
    'app.templateCreatedSuccessfully': 'Template created successfully',
    'app.templateUpdatedSuccessfully':'Template updated successfully',
    'app.add':'Add',
    'app.editContentTemplate': 'Edit content template',
    'app.edit':'Edit',
    'app.close':'Close',
    'app.cancel':'Cancel',
    'app.save':'Save',
    'app.min3Char': 'Min 3 Char',
    'app.max3Char':'Max 3 Char',
    'app.nameRequired': 'Name Required',
    'app.editorCodingRequired':'Editor Coding Required ',
    'app.typeRequired':'Type required',
    'app.itIsAMandatoryField':'.It is a mandatory field',
    'app.mustBe50CharactersOrLess':'Must be 50 characters or less ',
    'app.noTemplateFound.':'No template found.',
    'app.templateCreatedSuccessfully':'Template created successfully',
    'app.somethingWentwrongPleaseTryAgain':'Something went wrong, please try again.',
    'app.templateUpdatedSuccessfully':'Template updated successfully',
    'app.providesAnExampleOnHowToActivate' : 'Provides an example on how to activate',
    'app.deleteTemplate':'Delete Template',
    'app.delete':'Delete',
    'app.forEntandolabels':'for Entando labels',
    'app.inlineEditingAssistan':'Inline editing assist',
    'app.openA':'Open a',
    'app.tag':'TAG',
    'app.likeDivPSpan':'like div p span...' ,
    'app.addTheClass':'Add the class ',
    'app.editContent':'editContent',
    'app.toTheTAGKeepInMindThat':'to the TAG. Keep in mind that',
    'app.editContentText':'editContentText',
    'app.classCanBeUsedInCaseOfATextArea':'class can be used in case of a text-area.',
    'app.thenAdd':'Then add',
    'app.dataContentId':'data-content-id',
    'app.contentGetId':'$content.getId()',
    'app.thenAddTheAttributeIdTitleOfTheDesideredLabelAdding':'Then add the attribute ID (TITLE) of the desidered label adding',
    'app.dataAttrIdTitle':'data-attr-id="TITLE"',
    'app.andCloseTheTagWith':'and close the tag with',
    'app.pleaseBeCarefulWhenWritingTheAttributeIDasitis':"Please be careful when writing the attribute ID as it is",
    'app.caseSensitive':'case sensitive',
    'app.andItMustMatchTheLabelAttributeInTheNextStep':'and it must match the label attribute in the next step',
    'app.finallyAddTheLabelOfTheDesideredAttributeThatWillBeRenderedOnScreenWriting':'Finally add the label of the desidered attribute that will be rendered on screen writing',
    'app.closeThe':'Close the',
    'app.divPSpanOpenedAtTheVeryBeginning':'(div p span ...) opened at the very beginning.',
    'app.resultShouldLookLikeThis':'Result should look like this:',
    'app.noMatchesFound': 'No matches found',
    'app.firstPage': 'First Page',
    'app.previousPage': 'Previous Page',
    'app.currentPage': 'Current Page',
    'app.nextPage': 'Next Page',
    'app.lastPage': 'Last Page',
    'app.perPage': 'per page',
    'app.of': 'of',
    'app.templateDeletedSuccessfully':'Template deleted successfully',
    'app.providesTheAttributesListForTheSelectedCollectionType':'Provides the attributes list for the selected collection type.',
    'app.youCanInsertUpTo50Characters,IncludingUpperOrLowerCaseLettersNumbersAndSpecialCharacters':"You can insert up to 50 characters, including upper or lower case letters, numbers and special characters.",
    'app.selectOneExistingCollectionTypeToUseForTheContentTemplate':"Select one existing collection type to use for the content template.",
    'app.definesTheHTMLContentStructureUsingTheContentElementsDefinedByTheGivenCollectionType':"Defines the HTML content structure using the content elements defined by the given collection type.", 
    'app.providesAStylesheetFileToBeUsedWithTheHTMLModel':"Provides a stylesheet file to be used with the HTML model.",
    'app.loading': 'loading...'
    };