export default {
    'app.name':'Nome',
    'app.search':'Ricerca',
    'app.type':'Tipa',
    'app.all':'Tutte',
    'app.id':'Id',
    'app.actions':'Azioni',
    'app.styleSheet':'Foglio di stile',
    'app.inlineEditingAssistant':'Assistenza per la modifica in linea',
    'app.htmlModel':'Modello HTML',
    'app.code':'Codice',
    'app.attributes':'Attributi',
    'app.choose':'Scegliere...',
    'app.cancel':'Annulla',
    'app.save':'Salva',
    'app.requiredFields':'Campi richiesti',
    'app.addContentTemplate':'Aggiungi modello di contenuto',
    'app.pressCtrlSpaceToOpenContentAssistMenu':'(premi ctrl + spazio per aprire il menu di assistenza ai contenuti)',
    'app.noTemplateFound':'Nessun modello trovato',
    'app.doYouReallyWanttoDelete':'Vuoi davvero eliminare ?',
    'app.templateCreatedSuccessfully': 'Modello creato con successo',
    'app.somethingWentwrongPleaseTryAgain':'Qualcosa è andato storto, prova ancora',
    'app.templateUpdatedSuccessfully':'Modello aggiornato correttamente',
    'app.add':'Aggiungere',
    'app.editContentTemplate': 'Modifica modello di contenuto',
    'app.edit':'Modificare',
    'app.close':'Chiudi',
    'app.min3Char': 'Min 3 car',
    'app.max3Char':'Max 3 car',
    'app.nameRequired': 'Nome (obbligatorio',
    'app.editorCodingRequired':'Codifica delleditor richiesta',
    'app.typeRequired':'Digitare richiesto',
    'app.itIsAMandatoryField':'È un campo obbligatorio',
    'app.mustBe50CharactersOrLess':'Deve contenere massimo 50 caratteri ',
    'app.noTemplateFound.':'Nessun modello trovato',
    'app.templateCreatedSuccessfully':'Modello creato con successo',
    'app.somethingWentwrongPleaseTryAgain':'Qualcosa è andato storto. Per favore riprova.',
    'app.templateUpdatedSuccessfully':'Modello aggiornato correttamente',
    'app.providesAnExampleOnHowToActivate' :'Fornisce un esempio su come attivare',
    'app.deleteTemplate':'Elimina modello',
    'app.delete':'Elimina',
    'app.forEntandolabels':'per etichette Entando',
    'app.inlineEditingAssistan':'Assistenza per la modifica in linea',
    'app.openA':'Aprire un',
    'app.tag':'ETICHETTA',
    'app.likeDivPSpan':'come div p span...' ,
    'app.addTheClass':'Aggiungi la classe ',
    'app.editContent':'editContent',
    'app.toTheTAGKeepInMindThat':'modifica contenuto',
    'app.editContentText':'modificare il testo del contenuto',
    'app.classCanBeUsedInCaseOfATextArea':'class può essere usata nel caso di un area di testo. ',
    'app.thenAdd':'Poi aggiungi',
    'app.dataContentId':'data-content-id',
    'app.contentGetId':'$content.getId()',
    'app.thenAddTheAttributeIdTitleOfTheDesideredLabelAdding':"quindi aggiungere l'ID attributo (TITLE) dell'aggiunta dell'etichetta desiderata" ,
    'app.dataAttrIdTitle':'data-attr-id="TITLE"',
    'app.andCloseTheTagWith':'e chiudi il tag con',
    'app.pleaseBeCarefulWhenWritingTheAttributeIDasitis':"Si prega di prestare attenzione quando si scrive l'ID attributo così com'è",
    'app.caseSensitive':'maiuscole e minuscole',
    'app.andItMustMatchTheLabelAttributeInTheNextStep':'e deve corrispondere all attributo label nel passaggio successivo',
    "app.finallyAddTheLabelOfTheDesideredAttributeThatWillBeRenderedOnScreenWriting":"infine aggiungere l'etichetta dell'attributo desiderato che verrà renderizzato in screenwriting",
    'app.closeThe':'Chiudi il',
    'app.divPSpanOpenedAtTheVeryBeginning':"(div p span ...) si è aperto proprio all'inizio.",
    'app.resultShouldLookLikeThis':'Il risultato dovrebbe assomigliare a questo:',
    'app.noMatchesFound': 'Nessun risultato trovato',
    'app.firstPage': 'Prima pagina',
    'app.previousPage': 'Pagina precedente',
    'app.currentPage': 'Pagina corrente',
    'app.nextPage': 'Pagina successiva',
    'app.lastPage': 'Ultima pagina',
    'app.perPage': 'per pagina',
    'app.of': 'di',
    'app.templateDeletedSuccessfully':'Modello eliminato con successo',
    'app.providesTheAttributesListForTheSelectedCollectionType':"Fornisce l'elenco degli attributi per il tipo di raccolta selezionato.",
    'app.youCanInsertUpTo50Characters,IncludingUpperOrLowerCaseLettersNumbersAndSpecialCharacters':"È possibile inserire fino a 50 caratteri, comprese lettere maiuscole o minuscole, numeri e caratteri speciali.",
    'app.selectOneExistingCollectionTypeToUseForTheContentTemplate':"Seleziona un tipo di raccolta esistente da utilizzare per il modello di contenuto.",
    'app.definesTheHTMLContentStructureUsingTheContentElementsDefinedByTheGivenCollectionType':"Definisce la struttura del contenuto HTML utilizzando gli elementi del contenuto definiti dal tipo di raccolta specificato.", 
    'app.providesAStylesheetFileToBeUsedWithTheHTMLModel':"Fornisce un file di foglio di stile da utilizzare con il modello HTML.",
    'app.loading': 'Caricamento in corso...'
}